### ISSUE TITLE
Add theming for the "Chat with us" chatbox

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#13]

**Comment by wrex** [comment]
This one may be a bridge too far.

WK appears to be using inline styles in the markup for the chatbox.

**Comment by wrex** [comment]
I added a wontfix label. Please close this issue if you concur.

**Comment by Sepitus-exe** [comment]
The inline styles should be overrideable, but the classes are what worries me. Im not sure if they are user-specific or not. I would be inclined to believe that they are, as the names are complete jargon.

For now, I will leave this issue open, but since the priority is currently low, I will leave the wontfix flair up.

**Comment by wrex** [comment]
Since the chat facility is intended to contact WK for support, I'm strongly inclined not to touch the styling here. Bright and ugly is better than non-functional due to a bug in our code. The fact that the class names and inline styles appear to be auto-generated just adds more motivation not to fix this (becomes a game of whackamole with `!important` tags).

I'm going to close this one. Please reopen if you disagree.
