### ISSUE TITLE
Change of progress L/R bar color

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#36]
![image](https://user-images.githubusercontent.com/82216846/213061069-8fea78e2-277d-4207-a2e2-2b29e78c251e.png)

The upper progress bar should probably adapt the same color as is used by meaning bg. Might result in a more unified look with less clashing hue.

**Comment by wrex** [comment]
It uses `--ED-progress-clr` which is used for all the dashboards (reviews, lessons, dashboard).

It's okay to redefine `--ED-progress-clr` to be the same yellow as "meaning" but I think it's worth keeping all progress bars with consistent coloring.

I don't think we should change this.

**Comment by wrex** [comment]
I think your aesthetic concerns all tend to fall into the "this color clashes with that" category, by the way.

This would imply that the palette still needs work. I'm not convinced Bunpro is the best model to follow. WK has a different design hierarchy.

**Comment by wrex** [comment]
Another alternative: separate `--ED-meaning-SRS-progress`, `--ED-reading-SRS-progress`, and `--ED-overall-SRS-progress` colors.

More of a pain to implement, though.

**Comment by Sepitus-exe** [comment]
> I think your aesthetic concerns all tend to fall into the "this color clashes with that" category, by the way.

I will try to restrict myself from using this expression when it's not warranted. In this case, my issue was mostly with how busy the overall look felt. 3 elements are fighting for the attention of my eyesight, yet only two should be relevant. Marking another element in a distinct color undermines the effort to highlight the vocab and meaning/reading bar.

> This would imply that the palette still needs work. I'm not convinced Bunpro is the best model to follow. WK has a different design hierarchy.

It is true, that bunpro duesn't have as many different elements they need to highlight. Trying to achieve a similar look might be either impossible, or detrimental to page usability. I will think about it a bit more.

For now Im going to get some sleep. I should be able to get some little work done tomorrow, and do the rest of the bulk 2 days from now. Plenty of time to think about the palette.

**Comment by wrex** [comment]
Sleep is good. 

There is NO rush on any of this! Multi-day spans between changes should become the norm shortly.

On that note: I'm flying to the east coast tomorrow, spending some time with my mom (and attending a funeral for a friend over the weekend). I won't be back until next Thursday. I'll probably check in at least once or twice while I'm away, but one of the reasons I've been doing so much work on this (at a kinda crazy pace) is because I knew I'd be away.

The GREAT thing about git is that it's easy to see what's changed (or not) any time you look. There's no urgency to try and keep up with everything at all times.

**Comment by wrex** [comment]
> 3 elements are fighting for the attention of my eyesight, yet only two should be relevant

![image](https://user-images.githubusercontent.com/653208/213079109-709ff7f7-439d-46bb-a539-9f99d5ae6ba6.png)

Forgive me. I am NOT a designer by any stretch, but I have played a bit at product management, and I care about this sort of stuff. 

A WK lesson page displays a TON of information. I think this layout has the most important stuff appropriately emphasized (at least it isn't too far off):

Arguably, the hierarchy of informational importance is as follows:

1. What item am I getting quizzed on?  [The character 「千」]
2. Should I reply with the reading or the meaning? [meaning]
3. Is this a radical, kanji, or vocab item (which answer do they want)? [vocab]
4. What have I typed (so I can check before I hit enter)? [nothing yet]
5. How far along am I in my current batch of lessons? [1/5 or 20% of the way]
6. How many R/K/V remain in my lesson queue? [0/0/42]
7. How many lessons have I completed? [1]
8. What navigation options do I have away from this page? [home in UL,  useless kana IME table below, others unavailable]

While not perfect, I think this conveys things pretty well.

We can indicate hierarchy by size, contrast, color, and location (proximity and the well known ["Z-pattern"](https://www.creativebloq.com/ux/how-human-eye-reads-website-111413463)).

1. The most important information is huge, in the middle of the screen, and surrounded by color.
2. "Meaning" is also a pretty big blob of unique color, and the word "meaning" is bold and almost as large as the character.
3. That it's a vocabulary word is emphasized in two ways: green color and the regular-weight but still large word "vocabulary". I wasn't around when WK designed this page, but my feedback would have been that the item type is a bit _too_ prominent: that huge swath of green is almost the most important thing on the screen. I'd have suggested keeping the bulk of the field around the character gray, with maybe just a "tag" or leftmost border of green (and containing the word "vocabulary".
4. The input field is nice and prominent. Hard to miss.
5. Since the progress bar doesn't come in until 5 on the list, I'd say the small size is warranted. Honestly, on the default WK site I didn't even know it was even there until around level 45! The color is possibly a little too high contrast, and having it on the very top perhaps isn't ideal, but these are quibbles.
6. Items down this low in the hierarchy are too unimportant to worry about. I've got some quibbles, but none really matter.

I suspect your biggest issue isn't the visual hierarchy, it's the aesthetics of _that particular shade of red_ over _that particular shade of green_ (they are poorly related)! From a purely color theory perspective, the green should be #459B9D for it to be truly complementary to the red (#9D4745).

This is _precisely_ why I prefer to work in HSL for this kind of stuff. It isn't at all obvious that `#9d4745` and `#459b9d` have any sort of relationship whatsoever (or that `#9d4745` and `#58b09c` don't). But it's immediately obvious that `hsl(1, 39%, 44%)` and `hsl(181 39% 44%` do -- their saturation and lightness are identical and they are exactly 180 degrees apart on the color wheel!!

**Comment by wrex** [comment]
Need to make a call here:

Should we:

1. Use one color for all progress indicators (dashboard, lessons, reviews)? (current implementation)
2. Use different one color on dashboard, and a different one (perhaps grays) on lessons/reviews?
3. Use different colors: but change lessons/reviews depending on whether it's a meaning/reading quiz?

I think 3 is unnecessarily complex and potentially confusing to the users.

I'm okay with 1 (current implementation) but could also support 2.

Aesthetics should be your call for sure. Please let me know your preference and either implement or assign back to me.
