### ISSUE TITLE
Easy palette switching

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#54]
After working a bit on the ultimate timeline and creating the WK color spin. I got a slightly insane idea.

We could make the colors in the main theme themself inheritable from another separate css file that would contain nothing but the color palette. It might be an overload on how many styles you need to have active in stylus, but it would allow us to maintain multiple color pallets at once with a single main style sheet.

As things stand now, the WK color spin is already missing the fixes to the search bar and profile/setting pages.

**Comment by wrex** [comment]
Way ahead of you here.  :smile:

I'd already planned to create my own overrides of the top level props in a separate file.

It's still going to be a couple days at least before I can look at any of this. I'll be driving back up to my mom's tomorrow. Hope to have a little time before I fly home Thursday, but can't guarantee it.

I'm sure I'll like all your changes.

**Comment by wrex** [comment]
It occurs to me that we need a naming convention for any custom props used in the CSS rules themselves (not the top rule for :root). We need to make it obvious which props *must* be defined. I think we should avoid referring to any palette colors directly. Users can create whatever color palette they want as long as the mandatory props are defined (using those colors or anything else).

Eventually, once we are firm on a reasonable set of default colors, we should go through all the rules and add fall back defaults.

**Comment by Sepitus-exe** [comment]
I mostly agree, but isn't this a solved issue? There already is a naming convention, namely `--ED-` + short description. Distinguishing if a variable is omittable or mandatory comes down to whether it's semantically or statically named(e.g. `--ED-surface-1` vs `--ED-red`). This distinction is already explained within the comments of the `:root` if I'm not mistaken.

Some rules currently use static variables, which isn't optimal. I will take a look at them and try to change them to semantic ones. This might result in a few new variables.

When it comes to putting fallback colors in the rules, I don't currently see a need for it. There shouldn't be a situation, where the variable isn't defined, since it isn't reliant on any outside inheritance or definition. It could make sense if we decide to move the `:root` along with all the variable definitions outside the main file, but that's not what we are doing as of yet.

**Comment by wrex** [comment]
Yeah, I suppose you're right. The semantic/static distinction probably suffices.

> Some rules currently use static variables, which isn't optimal.

This is mostly what I was getting at, but I think its important that the main file contains all the info for the official wanikani site.

I'm thinking it might be best if users never edit the main file directly. Rather than just editing the file to add their desired colors, they should create a separate css file that get's loaded after WKElementaryDark.css to load their desired colors. This is trivial if all the semantic variables use the fallback to load the default colors. If the user provides an override, that gets used, otherwise it uses the default. Most users just load one stylesheet. "Advanced" (or opinionated) users may load other stylesheets to change the defaults.

I changed the order of the `:root` rule so the (mandatory) semantic definitions came first, followed by any (optional) palette colors they might use. The palette colors aren't really necessary, and will almost certainly contain several unused colors, but they do make it easier to create a consistent, harmonious theme.

I'll make a stab at a new README this weekend for how to use the variables to create your own themes. I'll also include a section for script writers, recommending that they use `--ED-` semantic variable names in their own CSS so that they can automagically pick up ED colors if a custom stylesheet gets loaded.

**Comment by Sepitus-exe** [comment]
> The semantic variables could load user override variables (`--USER` or somesuch) if present, otherwise fall back to default values.

That's basically what I did with the ultimate timeline script. The whole thing uses its own prefix `--ED-UT` that inherits the values from the `--ED` variables if any are loaded, otherwise, it falls back to its hard-coded values.

I'm all for introducing a master override prefix, but it's worth considering where should the override happen. We could implement it into every single rule or just in the declaration of semantic `--ED` variables. I would lean towards doing it in the `--ED` var declaration as it's a simpler solution that would be more welcoming to any potential future changes.

**Comment by wrex** [comment]
> I would lean towards doing it in the `--ED` var declaration as it's a simpler solution that would be more welcoming to any potential future changes

I concur. KISS principle always applies.

I should have some time tonight to take a stab at what I'm thinking for your review. I'll put it in a branch with a new README and possibly my own take at a color scheme (in a separate stylesheet) to make it easier to see how it's all intended to work.

**Comment by wrex** [comment]
I'm going to close this issue since it's implemented in PR #65. Let's track any required changes there.
