### ISSUE TITLE
so ... ship it?

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#92]

**Comment by Sepitus-exe** [comment]
Yeah, I will get around to it this weekend. Till then, I would like to figure out the last chartreuse as well as do a last thorough inspection of each page.

On the chartreuse front, Im like 99% sure, its not being used, since I would expect to find it as a background color of this "はや". But there is still a possibility it is being used in lessons and/or reviews. Before I can verify that, I want to refrain from making any changes to the file.
![image](https://user-images.githubusercontent.com/82216846/217886683-a153d728-57b0-4b43-ae53-64047e44a6de.png)

**Comment by wrex** [comment]
Let's hold off for a few more days. I'm starting to get annoyed by the naming inconsistencies.

I think we should either be forward thinking and append to "-clr" to EVERYTHING (since we don't have props for anything _except_ colors at the moment), or we should remove the unneccessary "-clr" on some but not all props.

**Comment by Sepitus-exe** [comment]
Sounds reasonable.

I myself got used to the current way but must admit, that having stuff like `--ED-text-clr` and `--ED-text-invcerted` feels odd.

Going through the file I recalled a few other things that were discussed, but never put up as issues, that might have to be done. I will write it all up and hopefully, we can get things done by Wednesday. This deadline is arbitrary and is subject to change as things develop.

**Comment by wrex** [comment]
Targeting a date is good. Real artists ship. :smile:

I was particularly irked by, e.g., `—ED-correct` not getting the suffix.
Could never remember which ones have it and which don’t.

**Comment by wrex** [comment]
Everything okay? I haven't heard from you for a few days. No worries if you're just busy at school, just checking in.

**Comment by Sepitus-exe** [comment]
Yeah I'm fine. Sorry for ghoting the project since Tuesday. I've been busy with some stuff that I don't want to get into. As you might have noticed by now, communication isn't one of my strong sides, but I will try my best to let you know next time.

I should be able to review your pull request and do the last changes on Monday. Possibly tomorrow if things work out.

**Comment by wrex** [comment]
No worries!

Take your time. Just wanted to make sure you were okay (and that I hadn't scared you off with that last PR).

**Comment by Sepitus-exe** [comment]
Guess it's time to ship it.

I will do one last round of checks, upload the files to userstyles.world and prepare an update to the WK forum page

**Comment by wrex** [comment]
Hooray! Don't forget to update the README links before publishing.
