### ISSUE TITLE
Add @-moz-document wrapper and metadata header to the main file

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#98]
After some deliberation, I decided that having a development file that differs from the officially released one is probably not a wise idea.

This will make a mess out of the spacing again, but I believe it's for the better we bite the bullet now, before the versions unexpectedly diverge in the future.

**Comment by Sepitus-exe** [comment]
Before doing so, I would like to make sure, there aren't any unmerged branches that might take an issue with such a drastic change. I will wait for you @wrex to give me the go-ahead.

**Comment by wrex** [comment]
I'm not following.

If the issue is two space or four space tabs, we just need to be consistent.

We are currently using 2 space.

I thought the stylus in-browser editor also had a setting for 2-space, but if you'd prefer to set it to four it's easy enough to add a vscode configuration file to the repository to use 4 (so I don't accidentally screw it up again)

**Comment by Sepitus-exe** [comment]
Oh, looks like I made some incorrect assumptions. I thought introducing the `@-moz-document domain("www.wanikani.com")` would cause an additional layer of indentation, which seems to not be the case looking at the exported code from stylus.

![image](https://user-images.githubusercontent.com/82216846/218278286-730a9f09-7c75-4f67-a401-afa4d35d3170.png)
